X <- toyModel("Tucker")

out1_1 <- NTD(X, rank=c(3,3,3), algorithm="Frobenius", num.iter=2)
out1_2 <- NTD(X, rank=c(3,3,3), algorithm="Frobenius", init="ALS", num.iter=2)
out1_3 <- NTD(X, rank=c(3,3,3), algorithm="Frobenius", init="Random", num.iter=2)
out2 <- NTD(X, rank=c(3,3,3), algorithm="KL", num.iter=2)
out3 <- NTD(X, rank=c(3,3,3), algorithm="IS", num.iter=2)
out4 <- NTD(X, rank=c(3,3,3), algorithm="Pearson", num.iter=2)
out5 <- NTD(X, rank=c(3,3,3), algorithm="Hellinger", num.iter=2)
out6 <- NTD(X, rank=c(3,3,3), algorithm="Neyman", num.iter=2)
out7 <- NTD(X, rank=c(3,3,3), algorithm="Alpha", num.iter=2)
out8 <- NTD(X, rank=c(3,3,3), algorithm="Beta", num.iter=2)
out9 <- NTD(X, rank=c(3,3,3), algorithm="HALS", num.iter=2)

expect_equivalent(length(out1_1), 2)
expect_equivalent(length(out1_2), 2)
expect_equivalent(length(out1_3), 2)
expect_equivalent(length(out2), 2)
expect_equivalent(length(out3), 2)
expect_equivalent(length(out4), 2)
expect_equivalent(length(out5), 2)
expect_equivalent(length(out6), 2)
expect_equivalent(length(out7), 2)
expect_equivalent(length(out8), 2)
expect_equivalent(length(out9), 2)
