X <- toyModel("NMF")

out1 <- NMF(X, J=3, algorithm="Frobenius", num.iter=2)
out2 <- NMF(X, J=3, algorithm="KL", num.iter=2)
out3 <- NMF(X, J=3, algorithm="IS", num.iter=2)
out4 <- NMF(X, J=3, algorithm="Pearson", num.iter=2)
out5 <- NMF(X, J=3, algorithm="Hellinger", num.iter=2)
out6 <- NMF(X, J=3, algorithm="Neyman", num.iter=2)
out7 <- NMF(X, J=3, algorithm="Alpha", num.iter=2)
out8 <- NMF(X, J=3, algorithm="Beta", num.iter=2)
out9 <- NMF(X, J=3, algorithm="HALS", num.iter=2)
out10 <- NMF(X, J=3, algorithm="PGD", num.iter=2)
out11 <- NMF(X, J=3, algorithm="GCD", num.iter=2)

expect_equivalent(length(out1), 4)
expect_equivalent(length(out2), 4)
expect_equivalent(length(out3), 4)
expect_equivalent(length(out4), 4)
expect_equivalent(length(out5), 4)
expect_equivalent(length(out6), 4)
expect_equivalent(length(out7), 4)
expect_equivalent(length(out8), 4)
expect_equivalent(length(out9), 4)
expect_equivalent(length(out10), 4)
expect_equivalent(length(out11), 4)
