X <- toyModel("NMF")

out1 <- NMF(X, num.iter=2, runtime=30, rank.est=TRUE, rank.method="all")
out2 <- NMF(X, num.iter=2, runtime=30, rank.est=TRUE, rank.method="cophenetic")
out3 <- NMF(X, num.iter=2, runtime=30, rank.est=TRUE, rank.method="dispersion")
out4 <- NMF(X, num.iter=2, runtime=30, rank.est=TRUE, rank.method="rss")
out5 <- NMF(X, num.iter=2, runtime=30, rank.est=TRUE, rank.method="evar")
out6 <- NMF(X, num.iter=2, runtime=30, rank.est=TRUE, rank.method="residuals")
out7 <- NMF(X, num.iter=2, runtime=30, rank.est=TRUE, rank.method="silhouette")
out8 <- NMF(X, num.iter=2, runtime=30, rank.est=TRUE, rank.method="silhouette.basis")
out9 <- NMF(X, num.iter=2, runtime=30, rank.est=TRUE, rank.method="silhouette.coef")
out10 <- NMF(X, num.iter=2, runtime=30, rank.est=TRUE, rank.method="silhouette.consensus")
out11 <- NMF(X, num.iter=2, runtime=30, rank.est=TRUE, rank.method="sparseness")
out12 <- NMF(X, num.iter=2, runtime=30, rank.est=TRUE, rank.method="sparseness.basis")
out13 <- NMF(X, num.iter=2, runtime=30, rank.est=TRUE, rank.method="sparseness.coef")
out14 <- NMF(X, num.iter=2, runtime=30, rank.est=TRUE, rank.method="sparseness2")
out15 <- NMF(X, num.iter=2, runtime=30, rank.est=TRUE, rank.method="sparseness2.basis")
out16 <- NMF(X, num.iter=2, runtime=30, rank.est=TRUE, rank.method="sparseness2.coef")
out17 <- NMF(X, num.iter=2, runtime=30, rank.est=TRUE, rank.method="entropy")
out18 <- NMF(X, num.iter=2, runtime=30, rank.est=TRUE, rank.method="entropy.basis")
out19 <- NMF(X, num.iter=2, runtime=30, rank.est=TRUE, rank.method="entropy.coef")
out20 <- NMF(X, num.iter=2, runtime=30, rank.est=TRUE, rank.method="singular")
out21 <- NMF(X, num.iter=2, runtime=30, rank.est=TRUE, rank.method="volume")
out22 <- NMF(X, num.iter=2, runtime=30, rank.est=TRUE, rank.method="condition")

# expect_equivalent(length(out1), 4)
